version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t travisgideonwong/m4-devop-assignment4-5-1:latest .
      - run:
          name: Login to Docker Hub
          command: echo mypassword | docker login -u myusername --password-stdin
      - run:
          name: Push Docker Image
          command: docker push travisgideonwong/m4-devop-assignment4-5-1:latest

workflows:
  version: 2
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
